import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <div className="p-8">
            <Head>
                <title>Nextjs Tailwind Starter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen px-16 py-0 flex flex-col flex-1 justify-center items-center">
                <h1 className="text-center text-[4rem] leading-[1.15] m-0">
                    Welcome to{" "}
                    <a className="text-blue-600 no-underline hover:underline focus:underline active:underline" href="https://nextjs.org">
                        Next.js!
                    </a>
                </h1>

                <p className="text-center mx-16 my-0 leading-6 text-2xl">
                    Get started by editing <code className="bg-[#fafafa] rounded-md p-3 text-lg">pages/index.js</code>
                </p>

                <div className="flex items-center justify-center flex-wrap md:max-w-[800px] w-full md:flex-row flex-col">
                    <a
                        href="https://nextjs.org/docs"
                        className="m-1 p-6 text-left text-inherit no-underline border border-[#eaeaea] rounded-[10px] transition-all max-w-[300px] hover:text-[#0070f3] hover:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]  focus:text-[#0070f3] focus:border-[#0070f3]">
                        <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Documentation &rarr;</h2>
                        <p className="m-0 text-xl leading-6">Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a
                        href="https://nextjs.org/learn"
                        className="m-1 p-6 text-left text-inherit no-underline border border-[#eaeaea] rounded-[10px] transition-all max-w-[300px] hover:text-[#0070f3] hover:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]  focus:text-[#0070f3] focus:border-[#0070f3]">
                        <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Learn &rarr;</h2>
                        <p className="m-0 text-xl leading-6">Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className="m-1 p-6 text-left text-inherit no-underline border border-[#eaeaea] rounded-[10px] transition-all max-w-[300px] hover:text-[#0070f3] hover:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]  focus:text-[#0070f3] focus:border-[#0070f3]">
                        <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Examples &rarr;</h2>
                        <p className="m-0 text-xl leading-6">Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className="m-1 p-6 text-left text-inherit no-underline border border-[#eaeaea] rounded-[10px] transition-all max-w-[300px] hover:text-[#0070f3] hover:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]  focus:text-[#0070f3] focus:border-[#0070f3]">
                        <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Deploy &rarr;</h2>
                        <p className="m-0 text-xl leading-6">Instantly deploy your Next.js site to a public URL with Vercel.</p>
                    </a>
                </div>
            </main>
            <footer className="flex items-center justify-center flex-grow">
                <a
                    className="flex items-center justify-center flex-grow"
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer">
                    Powered by{" "}
                    <span className="ml-2 h-4">
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
